name: 618 Tactical Cloud Sync

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Sync Script
        env:
          GPORTAL_IP: ${{ secrets.GPORTAL_IP }}
          GPORTAL_USER: ${{ secrets.GPORTAL_USER }}
          GPORTAL_PASS: ${{ secrets.GPORTAL_PASS }}
        run: python GPortalSync.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "618-Bot"
          git config --global user.email "bot@618crew.com"
          if [ -f "live_vault.xml" ]; then
            git add live_vault.xml
            git commit -m "Update Vault Data" || exit 0
            git push
          else
            echo "File live_vault.xml not found, skipping push."
            exit 1
          fi
