name: 618 Tactical Cloud Sync
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Sync
        env:
          GPORTAL_IP: ${{ secrets.GPORTAL_IP }}
          GPORTAL_USER: ${{ secrets.GPORTAL_USER }}
          GPORTAL_PASS: ${{ secrets.GPORTAL_PASS }}
        run: python GPortalSync.py
      - name: Commit Changes
        run: |
          git config --global user.name "618-Bot"
          git config --global user.email "bot@618crew.com"
          git add live_vault.xml
          git commit -m "Update Vault" || exit 0
          git push
